### ISSUE TITLE
error after update to 2.0.2

### ISSUE THREAD

**Issue by pikiton** [unipept/unipept-desktop#273] opened 2024-08-09 15:14 UTC
I get an error after update Unipept desktop to versiob 2.0.2. I get it after runnung new task, old tasks work correct 
![pict1](https://github.com/user-attachments/assets/9ffe88b5-fa8d-486b-b6e1-612a2d15ae76)

**Comment by pverscha** [comment] 2024-08-09 15:28
Hi @pikiton,

Thank you for contacting us. The problem is an issue on our side that will be fixed soon. In the meantime, however, you can go to "settings" in the desktop app and remove the URL endpoint ("https://api.unipept.ugent.be/", the one with a trailing slash at the end). After doing so, you can add the sample again to the desktop app and start a new analysis. The problem should not occur then.

**Comment by pverscha** [comment] 2024-08-19 12:43
This issue has been resolved by making changes to the API of Unipept. These changes have been published in https://github.com/unipept/unipept-api/pull/38

**Closed as completed by pverscha** 2024-08-19 12:43 UTC
